[package]
name = "backend"
version = "0.1.0"
edition = "2021"


[dependencies]
sqlx = {version="0.7", features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "uuid", "chrono"]
chrono = "0.4.34"
axum = "0.7.4"
tokio = {version = "1.36.0", features = ["full"]}
tower = "0.4.13"
